-- Run this once in your Supabase SQL editor.
create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null,
  seconds integer not null,
  created_at timestamptz default now()
);

alter table public.quiz_scores enable row level security;

create policy "Anyone can submit quiz scores"
on public.quiz_scores for insert
to anon
with check (char_length(name) between 1 and 24 and score between 0 and 150 and seconds >= 0);

create policy "Anyone can read leaderboard"
on public.quiz_scores for select
to anon
using (true);

-- Optional: remove all scores before a new event.
-- truncate table public.quiz_scores;